# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - sail
    r:
        build:
            context: ./docker/R/
            dockerfile: Dockerfile
        image: r
        expose:
            - '6311'
        networks:
            - sail
